[versions]
agp = "8.5.0"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"
yukiHookApi = "1.2.1"
dexkit = "2.0.1"

[libraries]
yukiHookApi = { module = "com.highcapable.yukihookapi:api", version.ref = "yukiHookApi" }
yukiHookKsp = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yukiHookApi" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
xposedApi = { module = "de.robv.android.xposed:api", version = "82" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
