name: Build LSPosed APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle unzip

      - name: Build APK with debug/test signing
        run: |
          cd $GITHUB_WORKSPACE
          # 使用 Gradle 的 debug 签名构建可直接安装 APK
          gradle assembleRelease -Pandroid.injected.signing.store.file=app/debug.keystore \
                                 -Pandroid.injected.signing.store.password=android \
                                 -Pandroid.injected.signing.key.alias=androiddebugkey \
                                 -Pandroid.injected.signing.key.password=android --console=plain

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BatteryTempStatus_LSPosed-release
          path: app/build/outputs/apk/release/app-release.apk
