name: Build LSP APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false

    # 2. 设置 Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    # 3. 安装 Android SDK
    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT
        sudo apt-get update
        sudo apt-get install -y unzip wget lib32z1 lib32stdc++6
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    # 4. 配置 local.properties
    - name: Configure local.properties
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

    # 5. Grant executable for Gradle wrapper
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 6. Build APK
    - name: Build Release APK
      run: ./gradlew clean assembleRelease --no-daemon --warning-mode all

    # 7. Upload APK artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: LSP-Release-APK
        path: app/build/outputs/apk/release/*.apk
