name: Build LSPosed APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 安装 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ 下载并解压 Gradle 7.5
      - name: Install Gradle 7.5
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5-all.zip
          unzip -qq gradle-7.5-all.zip -d $HOME/gradle
          echo "$HOME/gradle/gradle-7.5/bin" >> $GITHUB_PATH
          gradle --version

      # 4️⃣ 构建 APK
      - name: Build APK
        run: gradle assembleRelease --console=plain

      # 5️⃣ 上传 APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BatteryTempStatus_LSPosed-release
          path: app/build/outputs/apk/release/app-release.apk
