name: Build LSPosed APK

# 触发条件：push 到 main 分支 + 手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. 安装 Gradle
      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle unzip

      # 4. 构建 APK（测试签名）
      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          # 构建 release 版本并使用 debug.keystore 测试签名
          gradle assembleRelease -Pandroid.injected.signing.store.file=app/debug.keystore \
                                 -Pandroid.injected.signing.store.password=android \
                                 -Pandroid.injected.signing.key.alias=androiddebugkey \
                                 -Pandroid.injected.signing.key.password=android --console=plain

      # 5. 上传 APK 作为 artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BatteryTempStatus_LSPosed-release
          path: app/build/outputs/apk/release/app-release.apk
