name: Build LSP APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # 拉取仓库并初始化子模块
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # 安装 JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21

    # 安装 Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    # 确认 gradle wrapper 使用官方 URL
    - name: Ensure Gradle Wrapper
      run: |
        ./gradlew --version

    # 构建 Release APK
    - name: Build Release APK
      run: |
        ./gradlew clean assembleRelease --no-daemon --warning-mode all

    # 上传 APK 产物
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: LSP-Release-APK
        path: app/build/outputs/apk/release/*.apk
