name: Build LSP Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sdk-path: ${{ steps.sdk-path.outputs.android_home }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Cache Android SDK
        uses: actions/cache@v3
        id: sdk-cache
        with:
          path: android-sdk
          key: android-sdk-${{ hashFiles('**/build.gradle') }}
          restore-keys: android-sdk-

      - name: Setup Android SDK
        id: sdk-path
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: '34.0.0'
          cmdline-tools-version: '9123335'
          cache: true

      - name: Accept Android SDK licenses
        run: yes | ${{ steps.sdk-path.outputs.android_home }}/cmdline-tools/latest/bin/sdkmanager --licenses

  build:
    needs: setup
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-21-openjdk
      ANDROID_HOME: ${{ needs.setup.outputs.sdk-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Restore Android SDK cache
        uses: actions/cache@v3
        with:
          path: android-sdk
          key: android-sdk-${{ hashFiles('**/build.gradle') }}

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Use Gradle Wrapper with official URL
        run: |
          sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip|' gradle/wrapper/gradle-wrapper.properties

      - name: Parallel Gradle build
        run: |
          ./gradlew clean lintVitalRelease assembleRelease --parallel --max-workers=4 --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LSP-release-apk
          path: app/build/outputs/apk/release/*.apk
